import type { UnitCategory, UnitCategoryId, UnitDefinition } from './unit-converter.types'

export const UNIT_CATEGORY_IDS = ['length', 'weight', 'area', 'temperature', 'data'] as const

export const UNIT_CATEGORIES: UnitCategory[] = [
  { id: 'length', label: '길이' },
  { id: 'weight', label: '무게' },
  { id: 'area', label: '면적' },
  { id: 'temperature', label: '온도' },
  { id: 'data', label: '데이터' },
]

export const DATA_UNIT_NOTE = '데이터 단위는 10진수(1 KB = 1,000 B) 기준으로 계산합니다.'

export const UNITS_BY_CATEGORY: Record<UnitCategoryId, UnitDefinition[]> = {
  length: [
    {
      id: 'millimeter',
      categoryId: 'length',
      dimension: 'length',
      kind: 'linear',
      label: '밀리미터',
      symbol: 'mm',
      factorToBase: 0.001,
    },
    {
      id: 'centimeter',
      categoryId: 'length',
      dimension: 'length',
      kind: 'linear',
      label: '센티미터',
      symbol: 'cm',
      factorToBase: 0.01,
    },
    {
      id: 'meter',
      categoryId: 'length',
      dimension: 'length',
      kind: 'linear',
      label: '미터',
      symbol: 'm',
      factorToBase: 1,
    },
    {
      id: 'kilometer',
      categoryId: 'length',
      dimension: 'length',
      kind: 'linear',
      label: '킬로미터',
      symbol: 'km',
      factorToBase: 1000,
    },
    {
      id: 'inch',
      categoryId: 'length',
      dimension: 'length',
      kind: 'linear',
      label: '인치',
      symbol: 'in',
      factorToBase: 0.0254,
    },
    {
      id: 'foot',
      categoryId: 'length',
      dimension: 'length',
      kind: 'linear',
      label: '피트',
      symbol: 'ft',
      factorToBase: 0.3048,
    },
    {
      id: 'yard',
      categoryId: 'length',
      dimension: 'length',
      kind: 'linear',
      label: '야드',
      symbol: 'yd',
      factorToBase: 0.9144,
    },
    {
      id: 'mile',
      categoryId: 'length',
      dimension: 'length',
      kind: 'linear',
      label: '마일',
      symbol: 'mi',
      factorToBase: 1609.344,
    },
  ],
  weight: [
    {
      id: 'milligram',
      categoryId: 'weight',
      dimension: 'weight',
      kind: 'linear',
      label: '밀리그램',
      symbol: 'mg',
      factorToBase: 0.001,
    },
    {
      id: 'gram',
      categoryId: 'weight',
      dimension: 'weight',
      kind: 'linear',
      label: '그램',
      symbol: 'g',
      factorToBase: 1,
    },
    {
      id: 'kilogram',
      categoryId: 'weight',
      dimension: 'weight',
      kind: 'linear',
      label: '킬로그램',
      symbol: 'kg',
      factorToBase: 1000,
    },
    {
      id: 'ton',
      categoryId: 'weight',
      dimension: 'weight',
      kind: 'linear',
      label: '톤',
      symbol: 't',
      factorToBase: 1_000_000,
    },
    {
      id: 'geun',
      categoryId: 'weight',
      dimension: 'weight',
      kind: 'linear',
      label: '근',
      symbol: '근',
      factorToBase: 600,
    },
    {
      id: 'don',
      categoryId: 'weight',
      dimension: 'weight',
      kind: 'linear',
      label: '돈',
      symbol: '돈',
      factorToBase: 3.75,
    },
    {
      id: 'ounce',
      categoryId: 'weight',
      dimension: 'weight',
      kind: 'linear',
      label: '온스',
      symbol: 'oz',
      factorToBase: 28.349523125,
    },
    {
      id: 'pound',
      categoryId: 'weight',
      dimension: 'weight',
      kind: 'linear',
      label: '파운드',
      symbol: 'lb',
      factorToBase: 453.59237,
    },
  ],
  area: [
    {
      id: 'square-centimeter',
      categoryId: 'area',
      dimension: 'area',
      kind: 'linear',
      label: '제곱센티미터',
      symbol: 'cm²',
      factorToBase: 0.0001,
    },
    {
      id: 'square-meter',
      categoryId: 'area',
      dimension: 'area',
      kind: 'linear',
      label: '제곱미터',
      symbol: 'm²',
      factorToBase: 1,
    },
    {
      id: 'hectare',
      categoryId: 'area',
      dimension: 'area',
      kind: 'linear',
      label: '헥타르',
      symbol: 'ha',
      factorToBase: 10_000,
    },
    {
      id: 'square-kilometer',
      categoryId: 'area',
      dimension: 'area',
      kind: 'linear',
      label: '제곱킬로미터',
      symbol: 'km²',
      factorToBase: 1_000_000,
    },
    {
      id: 'acre',
      categoryId: 'area',
      dimension: 'area',
      kind: 'linear',
      label: '에이커',
      symbol: 'ac',
      factorToBase: 4046.8564224,
    },
    {
      id: 'pyeong',
      categoryId: 'area',
      dimension: 'area',
      kind: 'linear',
      label: '평',
      symbol: '평',
      factorToBase: 3.305785,
    },
  ],
  temperature: [
    {
      id: 'celsius',
      categoryId: 'temperature',
      dimension: 'temperature',
      kind: 'temperature',
      label: '섭씨',
      symbol: '°C',
    },
    {
      id: 'fahrenheit',
      categoryId: 'temperature',
      dimension: 'temperature',
      kind: 'temperature',
      label: '화씨',
      symbol: '°F',
    },
    {
      id: 'kelvin',
      categoryId: 'temperature',
      dimension: 'temperature',
      kind: 'temperature',
      label: '켈빈',
      symbol: 'K',
    },
  ],
  data: [
    {
      id: 'byte',
      categoryId: 'data',
      dimension: 'data',
      kind: 'linear',
      label: '바이트',
      symbol: 'B',
      factorToBase: 1,
    },
    {
      id: 'kilobyte',
      categoryId: 'data',
      dimension: 'data',
      kind: 'linear',
      label: '킬로바이트',
      symbol: 'KB',
      factorToBase: 1_000,
    },
    {
      id: 'megabyte',
      categoryId: 'data',
      dimension: 'data',
      kind: 'linear',
      label: '메가바이트',
      symbol: 'MB',
      factorToBase: 1_000_000,
    },
    {
      id: 'gigabyte',
      categoryId: 'data',
      dimension: 'data',
      kind: 'linear',
      label: '기가바이트',
      symbol: 'GB',
      factorToBase: 1_000_000_000,
    },
    {
      id: 'terabyte',
      categoryId: 'data',
      dimension: 'data',
      kind: 'linear',
      label: '테라바이트',
      symbol: 'TB',
      factorToBase: 1_000_000_000_000,
    },
  ],
}
